/**************************************************************************/
/*  donors.gen.h                                                          */
/**************************************************************************/
/*                         This file is part of:                          */
/*                             GODOT ENGINE                               */
/*                        https://godotengine.org                         */
/**************************************************************************/
/* Copyright (c) 2014-present Godot Engine contributors (see AUTHORS.md). */
/* Copyright (c) 2007-2014 Juan Linietsky, Ariel Manzur.                  */
/*                                                                        */
/* Permission is hereby granted, free of charge, to any person obtaining  */
/* a copy of this software and associated documentation files (the        */
/* "Software"), to deal in the Software without restriction, including    */
/* without limitation the rights to use, copy, modify, merge, publish,    */
/* distribute, sublicense, and/or sell copies of the Software, and to     */
/* permit persons to whom the Software is furnished to do so, subject to  */
/* the following conditions:                                              */
/*                                                                        */
/* The above copyright notice and this permission notice shall be         */
/* included in all copies or substantial portions of the Software.        */
/*                                                                        */
/* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,        */
/* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF     */
/* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. */
/* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY   */
/* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,   */
/* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE      */
/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                 */
/**************************************************************************/

/* THIS FILE IS GENERATED. EDITS WILL BE LOST. */

#pragma once

inline constexpr const char *DONORS_PATRONS[] = {
	"Khronos® Group <https://www.khronos.org/>",
	"OSS Capital <https://oss.capital/>",
	nullptr,
};

inline constexpr const char *DONORS_SPONSORS_PLATINUM[] = {
	"Scorewarrior <https://scwr.gg/godot>",
	"V-Sekai <https://github.com/V-Sekai>",
	"W4 Games <https://w4games.com/>",
	nullptr,
};

inline constexpr const char *DONORS_SPONSORS_GOLD[] = {
	"Mega Crit <https://www.megacrit.com/>",
	"Prehensile Tales <https://prehensile-tales.com>",
	"Robot Gentleman <http://robotgentleman.com/>",
	nullptr,
};

inline constexpr const char *DONORS_SPONSORS_SILVER[] = {
	"Bippinbits <https://bippinbits.com/>",
	"Broken Rules <https://brokenrul.es>",
	"Chasing Carrots <https://www.chasing-carrots.com>",
	"Copia Wealth Studios <https://copiawealthstudios.com/>",
	"LoadComplete <https://loadcomplete.com/>",
	"Null <https://null.com/>",
	"Orbital Knight <https://www.orbitalknight.com/>",
	"Playful Studios <https://playfulstudios.com/>",
	"Re-Logic <https://re-logic.com/>",
	nullptr,
};

inline constexpr const char *DONORS_MEMBERS_DIAMOND[] = {
	"ASIFA-Hollywood <https://www.asifa-hollywood.org/>",
	"Christina Coffin <https://bsky.app/profile/christinacoffin.bsky.social>",
	"Dominic Harris <https://wayfarer-games.com/>",
	"Kiri \"ExpiredPopsicle\" Artemis <https://expiredpopsicle.com/>",
	"Petr Kharitonov <https://petrkharitonov.com/>",
	"Seats.aero <https://seats.aero/>",
	"Sylv <https://rankith.itch.io/unnamed-space-idle-prototype>",
	"And 5 anonymous donors",
	nullptr,
};

inline constexpr const char *DONORS_MEMBERS_TITANIUM[] = {
	"Adriaan de Jongh <https://adriaan.games>",
	"Basically Games",
	"Draknek & Friends <https://www.draknek.org/>",
	"Garry Newman",
	"Gigabrain AI Reddit Search Engine <https://thegigabrain.com/?utm_source=godot>",
	"Jettelly <https://jettelly.com/>",
	"Justo Delgado Baudí <https://portfolio.mrcdk.com/>",
	"Kenney <https://kenney.nl/>",
	"Lucid Silence Games",
	"Matthew Hall <https://crossyroad.com/>",
	"PolyMars <https://polymars.dev/>",
	"Purple Moss Collectors <https://purplemosscollectors.com/>",
	"RPG in a Box <https://www.rpginabox.com>",
	"Starkandco <https://github.com/Starkandco>",
	"Studio Sunshower <https://www.studiosunshower.com/>",
	"TrampolineTales <https://TrampolineTales.com/>",
	"粟二华 (Su Erhua)",
	"And 4 anonymous donors",
	nullptr,
};

inline constexpr const char *DONORS_MEMBERS_PLATINUM[] = {
	"Andy Touch",
	"BlockImperiumGames (BIG)",
	"Bytten Studio",
	"Christopher Shifflett",
	"Cody Bentley",
	"Darrin Massena",
	"Fabio Alessandrelli",
	"HP van Braam",
	"iCommitGames",
	"Jason Hamilton",
	"Jonah Stich",
	"Josh Anthony",
	"Ludvig Temperli Risan",
	"Matthew Ekenstedt",
	"Memories in 8Bit",
	"Michael Martin",
	"Mike King",
	"Neal Gompa (Conan Kudo)",
	"Nico Ulriksen",
	"Nikita Blizniuk",
	"Raptor85",
	"Rémi Verschelde",
	"Ronnie Cheng",
	"Ryan Heath",
	"ShikadiGum",
	"Silver Creek Entertainment",
	"Stephan Kessler",
	"Stephen Rice",
	"And 14 anonymous donors",
	nullptr,
};

inline constexpr const char *DONORS_MEMBERS_GOLD[] = {
	"2 Nerdy Nerds",
	"73unny",
	"80px",
	"Abigail F.",
	"Admiral Potato",
	"afreytes",
	"AinaVT",
	"Ajat BlackSun",
	"Alex177Alex",
	"alMoo Games",
	"Alva Majo",
	"Andrew Eiche",
	"Antti Vesanen",
	"Arediss",
	"Asher Glick",
	"Axthelm",
	"BangTheWall",
	"Benito",
	"Benjamin Bridges",
	"Ben Rog-Wilhelm",
	"BetaTester704",
	"Brut",
	"Bryce Dixon",
	"Carlo Cabanilla",
	"Carlo del Mundo",
	"Carl van der Geest",
	"Chocolate Software",
	"Chris Backas",
	"Chris Lambson",
	"Christine Elisabeth Koppel",
	"Cindy Trieu",
	"ClarkThyLord",
	"Codex404",
	"cora",
	"Daniel Eichler",
	"Daniel Krafft",
	"Datzju",
	"David Chen Zhen",
	"David Coles",
	"David Hubber",
	"David Snopek",
	"Deakcor",
	"Delton Ding",
	"dgehrig",
	"Disco Cat",
	"Distorted Realities",
	"DitherDream",
	"Dominik Frizel",
	"Don't You Know Who I Am? Inc.",
	"Dustuu",
	"Dylan Dromard",
	"Edelweiss",
	"eelSkillz",
	"Emily Flion",
	"Ends",
	"Eren Ogrul",
	"Eric Brand",
	"Eric Phy",
	"Faisal Al-Kubaisi (QatariGameDev)",
	"Fanny Pack Studios",
	"Felix Adam",
	"FeralBytes",
	"Francisco Aliaga",
	"Francis Jasmin",
	"Frozen Fractal",
	"Gaudipern",
	"GetIntoGameDev",
	"GlassBrick",
	"Grau",
	"Grzegorz Wereszko",
	"Guangzhou Lingchan",
	"Guilherme Cattani",
	"Hayden Oliver",
	"hiulit",
	"https://domi.zip",
	"Huedeane",
	"Ikuti",
	"Illyan",
	"I.M.I.Self",
	"Immaculate Lift Studio",
	"Intrepid Marmot LLC",
	"Isaac Marovitz",
	"Ivan Tabashki",
	"jakemiki",
	"Jam",
	"Jason Cawood",
	"Jeff Hungerford",
	"Jesús Chicharro",
	"Johannes Wuensch",
	"John Gabriel",
	"Jonas Yamazaki",
	"Jonathan",
	"José Canepa",
	"Julian Todd",
	"Justin Laster",
	"Justin Sasso",
	"Kalydi Balázs",
	"KAR Games",
	"Kiryonn",
	"kodebold",
	"KOGA Mitsuhiro (@shiena)",
	"korinVR",
	"Kristian Kriehl",
	"KyletheDab",
	"Lars Thießen",
	"Lisandro Lorea (Red Mage Games)",
	"Logan Apple",
	"Luca Junge",
	"LyaaaaaGames",
	"m1n1ster",
	"Madison Nicole Videogames",
	"Mara Huldra",
	"Marek Belski",
	"Martin Šenkeřík",
	"Matthias B.",
	"Michael Alexsander",
	"Michael Gooch",
	"Michael Harrington",
	"Modus Ponens",
	"Moshe Harris",
	"Moth Soup",
	"Mr. Byte",
	"Muscarian Softworks",
	"Nassor Paulino da Silva",
	"Neuroticfly Games",
	"nezticle",
	"nikkehtine",
	"Niklas Wahrman",
	"Nitzan Bueno",
	"NotNet",
	"Oathbringer",
	"Officine Pixel",
	"ohanaya3",
	"Okatima AB",
	"Oscar Robin",
	"ovym",
	"Patrick Traynor",
	"Péter Horváth-Lázár",
	"Petr Maláč",
	"pirey",
	"protogames",
	"Rafa Laguna",
	"Reid Hannaford",
	"@reilaos",
	"Request",
	"re:thinc",
	"Richard Ivánek",
	"Robin Ward",
	"Ronny Mühle",
	"Rubén Rüger",
	"Samuel Judd",
	"Santi_FC",
	"Seref Karahan",
	"shazzner",
	"Shiny Shinken",
	"Silverclad Studios",
	"Skie Radscale",
	"Snow Diamond",
	"Sofox",
	"Space Kraken Studios",
	"Spoony Panda",
	"tenuki",
	"ThatGamer",
	"Thomas Lobig",
	"Tobias Bocanegra",
	"Tom Langwaldt",
	"Trevor Slocum",
	"tukon",
	"twitch.tv/RobitussinMD",
	"Tyler C",
	"Urban Protagonist",
	"Vincent Foulon",
	"Vojtech Lacina",
	"Voxel Floof",
	"Watchinofoye",
	"Yannick",
	"zikes",
	"Zoey Smith",
	"嗯大爷",
	"And 143 anonymous donors",
	nullptr,
};
